/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AvatarDropdown: typeof import('./src/components/GlobalHeader/AvatarDropdown.vue')['default']
    GlobalFooter: typeof import('./src/components/GlobalFooter/index.vue')['default']
    GlobalLoad: typeof import('./src/components/GlobalLoad/GlobalLoad.vue')['default']
    HenpayCard: typeof import('./src/components/HenpayCard/HenpayCard.vue')['default']
    HenpayDrChildren: typeof import('./src/components/HenpayTable/HenpayDrChildren.vue')['default']
    HenpayLayout: typeof import('./src/components/HenpayLayout/HenpayLayout.vue')['default']
    HenpayMenu: typeof import('./src/components/HenpayTable/HenpayMenu.vue')['default']
    HenpayTable: typeof import('./src/components/HenpayTable/HenpayTable.vue')['default']
    HenpayTableColState: typeof import('./src/components/HenpayTable/HenpayTableColState.vue')['default']
    HenpayTableColumns: typeof import('./src/components/HenpayTable/HenpayTableColumns.vue')['default']
    HenpayTextUp: typeof import('./src/components/HenpayTextUp/HenpayTextUp.vue')['default']
    HenpayUpload: typeof import('./src/components/HenpayUpload/HenpayUpload.vue')['default']
    RightContent: typeof import('./src/components/GlobalHeader/RightContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/HenpayLayout/SubMenu.vue')['default']
  }
}
